services: #define los contenedores que van a existir
  nginx:
    build: ./requeriments/nginx #docker construye la imagen usando el dockerfile en este directorio -> no usa imágenes prehechas
    container_name: nginx #construye el contenedor con ese nombre en vez de con nombres aleatorios
    env_file: #carga todas las variables de .env
      - .env
    ports:
      - "443:443" #VM escucha en 443:443, redirige a 443 el contenido nginx, único servicio expuesto al exterior
    volumes:
      - /home/amacarul/data/wordpress:/var/www/html #donde wordpress se instala, guarda themes, uploads... NGINX necesita leer estos archivos; wordpress y NGINX comparten volumen
    depends_on: #dependencias: arranca wordpress antes
      - wordpress
    networks: 
      - inception #crea una red privada docker
    restart: always

  wordpress:
    build: ./requeriments/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - /home/amacarul/data/wordpress:/var/www/html
    depends_on: #arranca mariadb antes
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requeriments/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/amacarul/data/mariadb:/var/lib/mysql #donde mariadb guarda db, tablas, users. Si se borra el contenedor, si no hay volumen, se pierde la base de datos. COn volumen, la base de datos persiste.
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
