# ==================================================================
# NGINX configuration
# This configuration defines a secure HTTPS web server capable of:
# 	- Serving static content from WordPress volumes
#	- Forwarding PHP requestes to the WordPress PHP-FPM container
#	- Using a self-signed TLS certificate for HTTPS
#
# Key design principles:
#	- TLS enabled with modern protocolos (TLSv1.2, TLSv1.3)
#	- Reverse proxying PHP requests to a dedicated container
#	- Minimal, stateless configuration: no application logic here
# ==================================================================
server {
	# --------------------------------------------------------------
	# Listening ports
	# --------------------------------------------------------------
	# Enable HTTPS on IPv4 and IPv6 addresses
	listen 443 ssl; # Listen on port 443 for IPv4 with SSL
	listen [::]:443 ssl; # Listen on port 443 for IPv6 with SSL

	# --------------------------------------------------------------
	# TLS/SSL configuration
	# --------------------------------------------------------------
	# Define supported TLS protocols
	ssl_protocols TLSv1.2 TLSv1.3;

	# Paths to the certificate and private key generated in Dockerfile
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	# --------------------------------------------------------------
	# Document root and default index files
	# --------------------------------------------------------------		
	root /var/www/html;	# Where NGINX serves file from
	index index.php index.html; # Default files to serve if URI points

	# Domain name for this server block
	server_name amacarul.42.fr; #Used for TLS SNI and host matching

	# --------------------------------------------------------------
	# Location block for static files
	# --------------------------------------------------------------
	location / {
		# Try to serve the requested URI as a file, then as a directory
		# and if none exists, fallback to index-php with query strings
		try_files $uri $uri/ /index.php?$args;
		# $arg passes the original query string to index.php
	}

	# --------------------------------------------------------------
	# Location block for PHP processing
	# --------------------------------------------------------------
	location ~ \.php$ {
		# Split URI to separate the script name from path info
		fastcgi_split_path_info ^(.+\.php)(/.+)$;

		# Send PHP requests to the PHP-FPM container on port 9000
		fastcgi_pass wordpress:9000;

		# Default file to serve if URI points to a directory
		fastcgi_index index.php;

		# Include standard FastCGI parameters provided by NGINX
		include fastcgi_params;

		# Tell PHP-SHP the real path of the script to execute
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

		# Forward PATH_INFO for scripts using URLs like /script.php/extra/path
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
}
